@baseUrl = http://localhost:3010/api/customers
@id = 6aa65b99d9f389d0c4f4352c

### 1. GET all items
GET {{baseUrl}}

###

### GET customer group by date
GET http://localhost:3010/api/customers/group

###

### 2. CREATE a new item
# @name createItem
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "user",
  "model": "vivo v9",
  "IMEI": "09 999 9999"
}

###

### 3. UPDATE an item (uses ID from step 2 if using VS Code REST Client)
@itemId = 6a98d3077f5398f7ff7520a0

PUT {{baseUrl}}/{{itemId}}
Content-Type: application/json

{
  "name": "user_1",
  "model": "vivo v9_update",
  "IMEI": "09 999 9999"
}

###

### 4. DELETE an item
DELETE {{baseUrl}}/{{itemId}}
